### ISSUE TITLE
Starting Pimatic as a service

### ISSUE THREAD

**Issue by quotschmacher** [treban/docker-pimatic#2]
I think it would be useful to start Pimatic inside the container as a service. So the restart from the webinterface is possible.

**Comment by treban** [comment]
should be fixed with latest version. 
a hint, i have a node10 version of the image too.  treban/pimatic:node10

**Comment by quotschmacher** [comment]
thanks for the hint with node10.
pimatic as service now works. but restart only works, if container has proper restart policy. 

if you start the service with `service pimatic start && /bin/bash` it can be restarted without leaving the container.

**Comment by treban** [comment]
Yeah, you're right. But docker is designed to run a single process in the foreground. 
I think this is the most elegant solution. Docker can thus control the state of the process and the docker restart policy is exactly the way to control the action after a container termination. 
More important to me was that the log files from Pimatic are accessible via docker tools. In the daemon mode of pimatic the logs are written to a file.

**Comment by quotschmacher** [comment]
> after a container termination

that's the point... should the container be restarted after a plugin installation or pimatic (which is the container - i know...)


> log files from Pimatic are accessible via docker tools

that's a good point.
